# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.01.24
_src_path: gh:scientific-python/cookie
backend: setuptools621
email: ebrahim.ebrahim@kitware.com
full_name: Ebrahim Ebrahim
license: Apache
org: brain-microstructure-exploration-tools
project_name: abcd-microstructure-pipelines
project_short_description:
  Processing pipelines to extract brain microstructure from ABCD Study dMRI
url: https://github.com/brain-microstructure-exploration-tools/abcd-microstructure-pipelines
vcs: true
